### PR TITLE
changed default params so cyberglove luanches correctly

### PR DESCRIPTION
**Pull request by dg-shadow**

### CODE REVIEW

**Review by AndriyPt — APPROVED** [review]

**Review by toliver — CHANGES_REQUESTED** [review]
This looks wrong. DO NOT MERGE.

There is no version 1.
We only support versions 2 and 3.

The times were OK the way they were.
Conceptually we want the point to be shortly after the beginning of the trajectory (as it is a single point trajectory) That's why **trajectory_delay** has to be very small (2 ms seems small enough).

**trajectory_tx_delay** is the one that has to be modified to account for the transmission time of the trajectory message from the cyberglove node to the hand trajectory_controller. We want it to be greater than the transmission time, so that the trajectory will still be valid when the trajectory_controller receives it.

The reason why we use timestamped trajectories instead of using stamp=0 is that this way we get rid of the jitter due to different TCP transmission times for different trajectory points.

**Comment by dg-shadow** [comment]
Ok, well why did it not work before, and it works now?

**Comment by dg-shadow** [comment]
These are the values that work from the config branch I've been using for testing.

**Comment by toliver** [comment]
"Not working" is very vague.
Version 1 is not contemplated in the driver. We only recognise versions 2 and 3. Your glove is version 2.

**Comment by dg-shadow** [comment]
version 1 and version 3 are treated identically in the driver
neither are contemplated directly.
version 2 is the only one which behaves differently

**Comment by dg-shadow** [comment]
default version is set to 3 now anyway, is that change enough to accept?

**Pull request closed without merging**
